name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -o theme.zip "https://wordpress.org/themes/download/wp-magazine.1.0.5.zip" 
          unzip theme.zip

      - name: Test Theme
        uses: StevenDufresne/wp-theme-validation-action-experiment@main
        with:
          root-folder: wp-magazine
