
## Create yml files
name: arcade-basic Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        uses: hmarr/debug-action@master
        
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://wordpress.org/themes/download/arcade-basic.1.1.2.zip"
          unzip theme.zip
      - name: Test My Theme
        env: 
          ACTIONS_RUNTIME_URL: "seomting"
          ACTIONS_CACHE_URL: "another thing"
          ACTIONS_RUNTIME_TOKEN: "again"
        uses: StevenDufresne/wp-theme-validation-action-experiment@add/keyboard-test
        with:
          root-folder: arcade-basic
          accessible-ready: false
