
## Create yml files
name: colibri-wp Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -o theme.zip "https://downloads.wordpress.org/theme/colibri-wp.1.0.80.zip"
          unzip theme.zip
      - name: Test My Theme
        uses: StevenDufresne/wp-theme-validation-action-experiment@add/keyboard-test
        with:
          root-folder: colibri-wp
          accessible-ready: false
