
## Create yml files
name: lyrical Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://downloads.wordpress.org/theme/lyrical.1.1.3.zip"
          unzip theme.zip
      - name: Test My Theme
        uses: StevenDufresne/wp-theme-validation-action-experiment@add/keyboard-test
        with:
          root-folder: lyrical
          accessible-ready: false
      - uses: actions/upload-artifact@v2
        with:
         name: screenshots
         path: ${{ steps.test.outputs.screenshots }} 
  
