
## Create yml files
name: mesmerize Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://downloads.wordpress.org/theme/mesmerize.1.6.97.zip"
          unzip theme.zip
      - name: Test My Theme
        uses: StevenDufresne/wp-theme-validation-action-experiment@add/keyboard-test
        with:
          root-folder: mesmerize
          accessible-ready: false
