
## Create yml files
name: oceanwp Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://downloads.wordpress.org/theme/oceanwp.1.9.0.zip"
          unzip theme.zip
      - name: Test My Theme
        id: test
        uses: StevenDufresne/wp-theme-validation-action-experiment@master
        with:
          root-folder: oceanwp
          accessible-ready: true
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ${{ steps.test.outputs.screenshots }}
