
## Create yml files
name: ratio-lite Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://wordpress.org/themes/download/ratio-lite.1.3.zip"
          unzip theme.zip
      - name: Test My Theme
        id: test
        uses: StevenDufresne/wp-theme-validation-action-experiment@add/keyboard-test
        with:
          root-folder: ratio-lite
          accessible-ready: false
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ${{ steps.test.outputs.screenshots }}
