
## Create yml files
name: twentyfifteen Theme Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Theme
        run: |
          curl -L -o theme.zip "https://downloads.wordpress.org/theme/twentyfifteen.2.7.zip"
          unzip theme.zip
      - name: Test My Theme
        id: test
        uses: tellyworth/wp-theme-validation-action-experiment@add/page-tests
        with:
          root-folder: twentyfifteen
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ${{ steps.test.outputs.screenshots }}
